version: '3.8'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html/new
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql:latest
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    volumes:
      - ./new:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php






# version: '3.8'
# services:
#   php:
#     build:
#       context: ./docker/php
#     volumes:
#       - ./src:/var/www/html
#     ports:
#       - 80:80
#     env_file:
#       - .env
#   mysql:
#     image: mysql:latest
#     volumes:
#       - ./docker/mysql/data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     ports:
#       - 3306:3306
